com.fasterxml.jackson.*:* = 2.13.3
com.fasterxml.uuid:* = 4.2.0
com.github.ben-manes.caffeine:* = 3.2.2
com.google.auto.service:* = 1.1.1
com.google.code.findbugs:* = 3.0.2
com.google.guava:guava = 33.4.8-jre
com.google.testing.compile:* = 0.23.0
com.palantir.delegate.processors:* = 2.0.0
com.palantir.jvm.diagnostics:* = 0.5.0
com.palantir.nylon:* = 0.4.0
com.palantir.safe-logging:* = 3.9.0
com.palantir.tracing:* = 6.27.0
com.palantir.javapoet:javapoet = 0.7.0
com.squareup.okhttp3:* = 5.1.0
# Keep major.minor metrics version in sync with Apache Spark
io.dropwizard.metrics:* = 4.2.36
io.undertow:* = 2.3.18.Final
net.bytebuddy:* = 1.17.7
net.jqwik:* = 1.9.3
org.assertj:* = 3.27.4
org.awaitility:* = 4.3.0
org.hdrhistogram:* = 2.2.2
org.junit.jupiter:* = 5.13.4
org.junit.platform:* = 1.13.4
org.mockito:* = 5.19.0
org.mpierce.metrics.reservoir:* = 1.1.3
org.openjdk.jmh:* = 1.37
org.slf4j:* = 2.0.17
uk.org.webcompere:system-stubs* = 2.1.6
