apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'org.revapi.revapi-gradle-plugin'

dependencies {
    api project(':tritium-annotations')
    api project(':tritium-api')
    api project(':tritium-core')
    api project(':tritium-registry')

    implementation 'com.google.guava:guava'
    implementation 'com.palantir.delegate.processors:delegate-processor'
    implementation 'com.palantir.javapoet:javapoet'
    implementation 'org.jspecify:jspecify'

    testImplementation 'com.google.testing.compile:compile-testing'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
}
