apply plugin: 'org.revapi.revapi-gradle-plugin'
dependencies {

    implementation 'com.palantir.safe-logging:preconditions'
    implementation 'com.palantir.safe-logging:safe-logging'
    implementation 'io.dropwizard.metrics:metrics-core'
    implementation 'org.jspecify:jspecify'
    implementation project(':tritium-api')
}
