apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'org.revapi.revapi-gradle-plugin'

dependencies {
    api project(':tritium-registry')

    implementation project(':tritium-caffeine')
    implementation 'com.github.ben-manes.caffeine:caffeine'
    implementation 'com.google.errorprone:error_prone_annotations'
    implementation 'com.google.guava:guava'
    implementation 'com.palantir.safe-logging:preconditions'
    implementation 'com.palantir.safe-logging:safe-logging'
    implementation 'com.palantir.tracing:tracing'
    implementation 'org.jspecify:jspecify'

    testImplementation 'com.palantir.tracing:tracing-api'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.junit.jupiter:junit-jupiter-api'
}
