/*
 * (c) Copyright 2019 Palantir Technologies Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.palantir.tritium.microbenchmarks;

@SuppressWarnings({"TooManyArguments", "TooManyParameters"}) // explicitly testing many arguments performance
public interface ManyArguments {
    void apply(
            int arg0,
            int arg1,
            int arg2,
            int arg3,
            int arg4,
            int arg5,
            int arg6,
            int arg7,
            int arg8,
            int arg9,
            int arg10,
            int arg11,
            int arg12,
            int arg13,
            int arg14,
            int arg15,
            int arg16,
            int arg17,
            int arg18,
            int arg19,
            int arg20,
            int arg21,
            int arg22,
            int arg23,
            int arg24,
            int arg25,
            int arg26,
            int arg27,
            int arg28,
            int arg29,
            int arg30,
            int arg31,
            int arg32,
            int arg33,
            int arg34,
            int arg35,
            int arg36,
            int arg37,
            int arg38,
            int arg39,
            int arg40,
            int arg41,
            int arg42,
            int arg43,
            int arg44,
            int arg45,
            int arg46,
            int arg47,
            int arg48,
            int arg49,
            int arg50,
            int arg51,
            int arg52,
            int arg53,
            int arg54,
            int arg55,
            int arg56,
            int arg57,
            int arg58,
            int arg59,
            int arg60,
            int arg61,
            int arg62,
            int arg63,
            int arg64,
            int arg65,
            int arg66,
            int arg67,
            int arg68,
            int arg69,
            int arg70,
            int arg71,
            int arg72,
            int arg73,
            int arg74,
            int arg75,
            int arg76,
            int arg77,
            int arg78,
            int arg79,
            int arg80,
            int arg81,
            int arg82,
            int arg83,
            int arg84,
            int arg85,
            int arg86,
            int arg87,
            int arg88,
            int arg89,
            int arg90,
            int arg91,
            int arg92,
            int arg93,
            int arg94,
            int arg95,
            int arg96,
            int arg97,
            int arg98,
            int arg99);

    enum Implementation implements ManyArguments {
        INSTANCE;

        @Override
        public void apply(
                int _arg0,
                int _arg1,
                int _arg2,
                int _arg3,
                int _arg4,
                int _arg5,
                int _arg6,
                int _arg7,
                int _arg8,
                int _arg9,
                int _arg10,
                int _arg11,
                int _arg12,
                int _arg13,
                int _arg14,
                int _arg15,
                int _arg16,
                int _arg17,
                int _arg18,
                int _arg19,
                int _arg20,
                int _arg21,
                int _arg22,
                int _arg23,
                int _arg24,
                int _arg25,
                int _arg26,
                int _arg27,
                int _arg28,
                int _arg29,
                int _arg30,
                int _arg31,
                int _arg32,
                int _arg33,
                int _arg34,
                int _arg35,
                int _arg36,
                int _arg37,
                int _arg38,
                int _arg39,
                int _arg40,
                int _arg41,
                int _arg42,
                int _arg43,
                int _arg44,
                int _arg45,
                int _arg46,
                int _arg47,
                int _arg48,
                int _arg49,
                int _arg50,
                int _arg51,
                int _arg52,
                int _arg53,
                int _arg54,
                int _arg55,
                int _arg56,
                int _arg57,
                int _arg58,
                int _arg59,
                int _arg60,
                int _arg61,
                int _arg62,
                int _arg63,
                int _arg64,
                int _arg65,
                int _arg66,
                int _arg67,
                int _arg68,
                int _arg69,
                int _arg70,
                int _arg71,
                int _arg72,
                int _arg73,
                int _arg74,
                int _arg75,
                int _arg76,
                int _arg77,
                int _arg78,
                int _arg79,
                int _arg80,
                int _arg81,
                int _arg82,
                int _arg83,
                int _arg84,
                int _arg85,
                int _arg86,
                int _arg87,
                int _arg88,
                int _arg89,
                int _arg90,
                int _arg91,
                int _arg92,
                int _arg93,
                int _arg94,
                int _arg95,
                int _arg96,
                int _arg97,
                int _arg98,
                int _arg99) {}
    }
}
